# Generated by Django 4.1.3 on 2022-12-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0002_user_gender_user_datails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_datails',
            old_name='users',
            new_name='user',
        ),
    ]
