# Generated by Django 4.1.3 on 2022-12-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0003_rename_users_user_datails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_datails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
