# Generated by Django 4.1.3 on 2022-12-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0004_alter_user_datails_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_datails',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
