# Generated by Django 4.1.3 on 2022-12-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0005_alter_user_datails_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_datails',
            old_name='user',
            new_name='user_id',
        ),
    ]
